### ISSUE TITLE
Add a plugin entry within the menu page + page

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman.github.io#55]
I suggest to add a plugin entry within the menu page + page presenting the following info as a table

| Name | Description | Protocol | Service Type | Doc Link |
| --- | --- | --- | --- | --- |
| Basic authentication | Basic HTTP authentication where account is verified using LDAP, JDBC or static list | HTTP(S) | REST, Web Service | REST or Web Service |

**Comment by EricWittmann** [comment]
Where would this table live?

**Comment by cmoulliard** [comment]
Should be under this project (web site)

**Comment by EricWittmann** [comment]
Right, but there are a lot of different pages.  Are you suggesting a new "Apiman Policies" page, or perhaps something in the User Guide?  Just curious.

**Comment by cmoulliard** [comment]
As the policies (and also the plugins) are important key concepts of the Apiman technology, they should be part of a dedicated web site page that why not, we can add as addendum to the user guide manual
