### ISSUE TITLE
Current status unclear

### ISSUE THREAD

**Issue by geertschuring** [apiman/apiman.github.io#75]
What is the current status of ApiMan? The website does not clearly communicate this, but seems abandoned.

**Comment by volkflo** [comment]
Hey @geertschuring,

the project is not under heavy development at the moment.
But there are still some very active community members as @bekihm, @tevosouza, and me. 

Our product is based on apiman, so we will contribute fixes and new features in the future.
See also this post from us: https://github.com/apiman/apiman/issues/801#issuecomment-580227817

Regards,
Florian

**Comment by EricWittmann** [comment]
I think @volkflo's answer is correct.  :)  I would describe the project as being in "maintenance" mode.  The community exists but is small - and we're certainly open to contributions.  Red Hat deprecated the project when we acquired 3scale (a dedicated API Management company).  But as a company we try never to abandon upstream projects, and so we continue to maintain Apiman.

**Comment by volkflo** [comment]
@geertschuring The new roadmap is soon available on the website :)

**Comment by bekihm** [comment]
@geertschuring The roadmap is now online:-)
